# Generated by Django 6.0.2 on 2026-03-02 12:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machinemodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(10)])),
                ('slug', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('in_stock', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_available', models.BooleanField(default=False)),
                ('machine_compatibility', models.ManyToManyField(to='machinemodel.machinemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
