# Generated by Django 6.0.2 on 2026-02-26 08:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
        ('part', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='model',
        ),
        migrations.AddField(
            model_name='part',
            name='machines',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='machine.machine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='part',
            name='serial_number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
