# Generated by Django 6.0.2 on 2026-02-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
