# Generated by Django 6.0.2 on 2026-03-02 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machinecategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=10)),
                ('weight', models.FloatField()),
                ('year', models.PositiveIntegerField()),
                ('machine_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='machinecategory.machinecategory')),
            ],
        ),
    ]
