# Generated by Django 6.0.2 on 2026-02-26 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='part',
            new_name='parts',
        ),
    ]
